name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: devshriram
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories
