name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Overview
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.overview.svg
          user: devshriram
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories
          config_display: large

      - name: Isocalendar
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.isocalendar.svg
          user: devshriram
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Introduction
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.introduction.svg
          user: devshriram
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_introduction: yes
          plugin_introduction_title: yes

      - name: Stargazers
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.stargazers.svg
          user: devshriram
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_stargazers: yes
          plugin_stargazers_charts: yes

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.achievements.svg
          user: devshriram
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_threshold: X
